apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub
  labels:
    app: hub
spec:
  selector:
    matchLabels:
      app: hub
  template:
    metadata:
      labels:
        app: hub
    spec:
      containers:
      - name: hub
        image: mlm55/jupyterhub_hub
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
        - name: notebook
          containerPort: 8081
        env:
        - name: HUB_CONNECT_IP
          value: hub
        - name: AGAVE_SERVICE_TOKEN
          value:
        - name: AGAVE_BASE_URL
          value: https://api.tacc.utexas.edu
        - name: TENANT
          value:
        - name: INSTANCE
          value:
        - name: TAS_URL_BASE
          value: https://tas.tacc.utexas.edu/api/v1
        - name: TAS_ROLE_ACCT
          value: tas-jetstream
        - name: TAS_ROLE_PASS
          value: