---
# tasks file for jupyterhub
- name: Add jupyterhub files
  copy:
    src: jupyterhub
    dest: /jupyterhub
  sudo: yes
  register: sources

- block:
    - name: Build image
      docker_image:
        name: jupyterhub
        path: /jupyterhub/jupyterhub
        state: build
      when: sources.changed
      sudo: yes
  rescue:
    - name: Remove sources
      file:
        path: /jupyterhub
        state: absent
      sudo: yes

    - fail: msg="Build image failed"

- name: Run the container
  docker:
    image: jupyterhub
    name: jupyterhub_1
    state: started
    expose:
      - 8000
    ports:
      - "80:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      OAUTH_CALLBACK_URL: http://129.114.6.51/hub/oauth_callback
      AGAVE_CLIENT_ID: iVlh5I4_I6I0b3_NJE2xTUfWAdYa
      AGAVE_CLIENT_SECRET: h4qMtPMGZH7DqsbFD2mA4Ssx9B0a
      AGAVE_BASE_URL: dev.tenants.staging.agaveapi.co
      AGAVE_TENANT_NAME: Staging
  sudo: yes
  register: container

- name: Ensure passlib
  local_action: pip name=passlib state=present
  sudo: yes
  
  
