---
# tasks file for jupyterhub
- name: Add jupyterhub files
  copy:
    src: jupyterhub
    dest: /jupyterhub
  sudo: yes
  register: sources

- block:
    - name: Build image
      docker_image:
        name: jupyterhub
        path: /jupyterhub/jupyterhub
        state: build
      when: sources.changed
      sudo: yes
  rescue:
    - name: Remove sources
      file:
        path: /jupyterhub
        state: absent
      sudo: yes

    - fail: msg="Build image failed"

- name: Run the container
  docker:
    image: jupyterhub
    name: jupyterhub_1
    state: started
    expose:
      - 8000
    ports:
      - "9000:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker/sock"
  sudo: yes
  register: container

- name: Ensure passlib
  local_action: pip name=passlib state=present
  sudo: yes
  
- debug: msg="{{ container }}"

- name: Create users
  user:
    name: "{{ item.username }}"
    uid: "{{ item.uid }}"
    password: "{{ lookup('password', '/tmp/passwordfile_'+item.username) | safe | password_hash('sha512') }}"
  with_items: users
  sudo: yes
  