---
# tasks file for jupyterhub
- name: Add jupyterhub files
  copy:
    src: jupyterhub
    dest: /jupyterhub
  sudo: yes
  register: sources

- name: Render jupyterhub config
  template:
    src: jupyterhub_config.py.j2
    dest: /jupyterhub/jupyterhub/jupyterhub_config.py
  sudo: yes
  
- name: See if the user image is available
  shell: "docker inspect {{ user_image }} >/dev/null 2>&1"
  args:
    warn: no
  sudo: yes
  changed_when: false
  ignore_errors: yes
  register: user_image_ok
  
- name: Pull jupyter image for users
  command: "docker pull {{ user_image }}"
  when: user_image_ok|failed
  sudo: yes
  register: user_image

- block:
    - name: Build image
      docker_image:
        name: jupyterhub
        path: /jupyterhub/jupyterhub
        state: build
      when: sources.changed or user_image.changed or force_build
      sudo: yes
  rescue:
    - name: Remove sources
      file:
        path: /jupyterhub
        state: absent
      sudo: yes

    - fail: msg="Build image failed"

- name: Run the container
  docker:
    image: jupyterhub
    name: jupyterhub_1
    state: reloaded
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tokens:/tokens"
    env:
      OAUTH_CALLBACK_URL: "{{ oauth_callback_url }}"
      AGAVE_CLIENT_ID: "{{ agave_client_id }}"
      AGAVE_CLIENT_SECRET: "{{ agave_client_secret }}"
      AGAVE_BASE_URL: "{{ agave_base_url }}"
      AGAVE_TENANT_NAME: "{{ agave_tenant_name }}"
  sudo: yes
  register: container

- name: Ensure passlib
  local_action: pip name=passlib state=present
  sudo: yes
  
- name: Ensure hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: '127.0.0.1 jupyterhub'
    state: present
  sudo: yes

