---
# defaults file for jupyterhub

user_image: jupyter/singleuser
oauth_callback_url: http://example.com
agave_client_id: client_id
agave_client_secret: client_secret
agave_base_url: example.com
agave_tenant_name: my tenant
