version: "2"

services:

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/cert.cer:/etc/ssl/jupyterhub/jupyterhub_staging_bundle.cer
      - ./nginx/ssl/key.pem:/etc/ssl/jupyterhub/jupyterhub_staging_bundle.pem
    ports:
      - "80:80"
      - "443:443"